group = io.canvasmc.baguette
version = 1.21.11-R0.1-SNAPSHOT

# This is the current API version for use in (paper-)plugin.yml files
# During snapshot cycles this should be the anticipated version of the release target
apiVersion = 1.21.11
mcVersion = 1.21.11

canvasCommit = a55c0bb1055dcd8ee3561d598c81750c73280bf2
foliaCommit = 1aa705513ed58a2e5683ca35957a39321b5cf09f
# A commit hash from your repository 
# to fetch from in order to bring in objects for 3-way apply.
# Replace `Baguette` with your fork's name capitalized.
# oldBaguetteCommit = ba1486d1975a7cbe7bfc5bd5ecf6b5bc1ca4f668

# ZOPTYMALIZOWANE DLA MAŁEGO RAM (6.84 GB)
org.gradle.configuration-cache = true
org.gradle.caching = true
org.gradle.parallel = false
org.gradle.vfs.watch = false
org.gradle.jvmargs = -Xmx2500M -XX:+UseG1GC -XX:MaxMetaspaceSize=256M
org.gradle.workers.max = 2
org.gradle.daemon = true
